# 机器人
alarm:
  url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=5d39b94d-30e1-4a2c-986d-c6a6821a4650
# 短信
sms:
  host: https://cdcxdxjk.market.alicloudapi.com
  path: /chuangxin/dxjk
  appcode: 0b8428b093f543a8aeaa7b6fa6db634b
# 身份证实名认证
idcard:
#  host: http://aliyunverifyidcard.haoservice.com
#  path: /idcard/VerifyIdcardv2
#  appcode: c2b9cd33f35e4710920a5d425f3651c9
  host: https://eid.shumaidata.com
  path: /eid/check
  appcode: 0b8428b093f543a8aeaa7b6fa6db634b
# 银行卡实名认证
bankcard:
#  host: https://tbank.market.alicloudapi.com
#  path: /bankCheck
#  appcode: c2b9cd33f35e4710920a5d425f3651c9
  host: https://bkcard3.market.alicloudapi.com
  path: /bankcard3/check
  appcode: 0b8428b093f543a8aeaa7b6fa6db634b


